### ISSUE TITLE
question

### ISSUE THREAD

**Issue by cike-567** [doanhmaple/Razer-Blade-15-Advanced-2018-Hackintosh#2]
I used your efi (the latest), the touchpad cannot be used, and the battery cannot be displayed normally. After I remove your upgraded part, it can be used normally

**Comment by doanhxd** [comment]
Sorry for the issue you're facing... I have the bad time with no battery in my laptop because it's got bulged after 1 year using and I just replaced yesterday so I've been uncheck the SSDT-BAT.aml and Patch for it in config... I was updated completely and most stable for other Razer Blade 15 Advanced 2018 users <3 Thank you for helping me better
